### ISSUE TITLE
Bug: CuTe scan path illegal-addresses on H100 (sm_90a) in v0.2.0, even on single visible GPU

### ISSUE THREAD

**Issue by b-vitamins** [b-vitamins/slinoss#9]
## Summary

On Hopper (`NVIDIA H100 80GB HBM3`), the accelerated CuTe scan path in `slinoss v0.2.0` crashes with `CUDA_ERROR_ILLEGAL_ADDRESS` in a minimal `SLinOSSMixer` forward pass.

This appears to be downstream-visible in `slinoss` but likely upstream to CUTLASS DSL. I am filing it here because it currently blocks accelerated state-carry training for a real `slinoss` consumer.

## Environment

- GPU: `NVIDIA H100 80GB HBM3`
- Python: `3.11`
- `slinoss`: `0.2.0`
- `torch`: `2.10.0`
- `nvidia-cutlass-dsl`: `4.4.2`
- `cuda-python`: `12.9.4`
- container base: `pytorch/pytorch:2.4.1-cuda12.4-cudnn9-devel`
- `CUTE_DSL_ARCH=sm_90a`
- repro also tested with only one visible GPU via `CUDA_VISIBLE_DEVICES=0`

## Minimal repro

```python
import torch
from slinoss.layers import (
    AutoCConv1dBackend,
    AutoScanBackend,
    AutoScanPrepBackend,
    ReferenceCConv1dBackend,
    ReferenceScanBackend,
    ReferenceScanPrepBackend,
    SLinOSSMixer,
)


def make_backend(kind, auto_cls, reference_cls):
    return auto_cls() if kind == "auto" else reference_cls()


device = torch.device("cuda")
dtype = torch.bfloat16

torch.manual_seed(0)

mixer = SLinOSSMixer(
    512,
    d_state=128,
    expand=2,
    d_head=64,
    d_conv=4,
    chunk_size=128,
    normalize_bc=True,
    scanprep_backend=make_backend("reference", AutoScanPrepBackend, ReferenceScanPrepBackend),
    backend=make_backend("auto", AutoScanBackend, ReferenceScanBackend),
    cconv_backend=make_backend("reference", AutoCConv1dBackend, ReferenceCConv1dBackend),
    device=device,
    dtype=dtype,
).to(device=device, dtype=dtype)

x = torch.randn(1, 128, 512, device=device, dtype=dtype)
torch.cuda.synchronize(device)
y = mixer(x)
torch.cuda.synchronize(device)
print(y.shape)
```

## Actual behavior

The final `torch.cuda.synchronize()` fails with:

```text
torch.AcceleratorError: CUDA error: an illegal memory access was encountered
```

## Backend isolation matrix

These were the same shape family and device, changing only backend selection:

- `scanprep=reference, scan=reference, cconv=reference`: passes
- `scanprep=auto, scan=reference, cconv=reference`: passes
- `scanprep=reference, scan=auto, cconv=reference`: fails with `CUDA_ERROR_ILLEGAL_ADDRESS`
- `scanprep=auto, scan=auto, cconv=auto`: fails with the same illegal-address crash

So the failing surface is the CuTe **scan** path, not `scanprep` and not causal conv.

## Statefulness

This is **not** specific to state carry. The same crash reproduces in both:

- stateless `y = mixer(x)`
- stateful `y, next_state = mixer(x, state=state, return_state=True)`

So the H100 problem appears to be broader than the recent stateful CuTe scan addition.

## Not the known non-zero logical device bug

There is a known upstream CUTLASS DSL issue pattern where multiple visible GPUs plus a non-zero logical CUDA device can crash due to device-id mishandling. A similar case is discussed here:

- https://github.com/suresh-meena/linoss/issues/6

However, this Hopper repro still fails when:

- only one GPU is visible (`CUDA_VISIBLE_DEVICES=0`)
- the process uses logical `cuda:0`
- `CUTE_DSL_ARCH=sm_90a` is set explicitly

So this does not appear to be explained by that existing device-index issue alone.

## Expected behavior

This mixer forward should either:

- run correctly on Hopper with the accelerated scan backend, or
- fail early with a clear unsupported-config error

It should not poison the CUDA context with an illegal memory access.

## Why this matters downstream

This currently blocks accelerated training on Hopper for `slinoss` consumers that use `SLinOSSMixer` as their main recurrent block. The non-accelerated reference path is fine; the blocker is specifically the CuTe scan path on H100.

**Comment by b-vitamins** [comment]
I dug into this and found a real correctness bug on the CuTe host-launch side that was introduced in `5848a47`.

The issue was that the new pointer cache keyed `cute.Pointer` objects only by raw address and dtype. Distinct tensor views that share a base address could therefore collapse onto the same cached `Pointer` object. In the `v2x2ssd` CuTe forward path that can happen for arguments like `K_f` and `K_f[..., 0, :]`, which should remain distinct host-wrapper arguments.

I fixed that locally by making the pointer-cache key include full tensor-view geometry (shape + stride) instead of just address/dtype, so same-base views no longer alias through the cache. I also added regression coverage for:

- the exact issue-9 mixer shape in BF16, comparing CuTe scan against the reference path
- low-level pointer-cache regressions for same-base tensor views in both `v2x2ssd` forward and scanprep helpers

Local validation on my side:

- `ruff check`
- `ruff format --check .`
- `pyright`
- `pytest` -> `110 passed`
- direct rerun of the issue-9 mixer shape locally in both stateless and stateful modes -> passes

Important caveat: I was **not** able to reproduce the illegal-address itself here because I do not have a Hopper/H100 in this environment; my local GPU is an RTX 3060. So I am treating this as a candidate root-cause fix, not as proven closure yet.

Local fix commit: `04f8151` (`fix: keep CuTe pointer caches distinct across views`)

The next step is to rerun the exact repro from this issue on H100 against that commit. If it clears both the stateless and stateful CuTe scan paths there, I think this issue can be closed.

**Comment by b-vitamins** [comment]
Another fix candidate for this Hopper issue is now on `master`: `2bc2c41` (`fix: align chunk scan start-state buffers`).

This one fixes a separate CuTe launcher/kernel contract bug on the forward scan path. The `chunk_scan` kernel does direct 16-byte vector loads from `Z0` / `chunk_starts`, but the Python launcher was not normalizing those buffers to 16-byte alignment before crossing the JIT boundary. That left the kernel relying on an alignment contract the launcher had not actually enforced.

The fix now forces 16-byte alignment for:
- the public `chunk_scan_cute(..., chunk_starts=...)` surface
- the fused `v2x2ssd_fwd_cute` path’s internal `chunk_starts` buffer before it is handed to the same scan kernel

I also added a direct regression that manufactures a real contiguous but under-aligned `float32` `chunk_starts` view via `as_strided(..., storage_offset=1)` on a supported scan shape, then proves the launcher rebuilds a 16-byte-aligned buffer before creating the CuTe pointer arg.

Validation on the fixing tree:
- `tests/test_v2x2ssd_cute.py -k "underaligned_chunk_starts or issue_9_shape"` -> `5 passed`
- `tests/test_mixer.py -k issue_9_bf16_shape` -> `1 passed`
- full gate -> `132 passed`
- matched direct `v2x2ssd_fwd_cute` timing at the real nextchar operator shape stayed flat (`4598.9 ms` on clean `99954c7` vs `4589.7 ms` on `2bc2c41`)

I am still intentionally keeping `#9` open because I still cannot run the original repro on H100 from here. At this point current `master` includes three separate issue-9-relevant forward fixes (`04f8151`, `99954c7`, `2bc2c41`), and the next useful step is still real Hopper confirmation.

**Comment by b-vitamins** [comment]
Fixed by 284144b (`fix: avoid hopper issue 9 chunk scan shuffle fault`). This addressed the H100 chunk-scan shuffle fault definitively, so closing.
